// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrfitufsdpzvppwyqrfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyZml0dWZzZHB6dnBwd3lxcmZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNzgzNzEsImV4cCI6MjA1MTg1NDM3MX0.Yk5RLGw_H-CX6hrOBFatGMFHoNLff79edCDrIACOAwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);